### ISSUE TITLE
Wrong MySQL char set

### ISSUE THREAD

**Issue by robertDouglass** [platformsh/platformsh-example-typo3#1]
From the status report:

MySQL Database Character Set    Wrong value detected
Your default database uses character set "latin1", but only "utf8" or "utf8mb4" is supported with TYPO3.

**Comment by bmack** [comment]
Hey Robert,

we found out that the platform mariaDB has a default charset of latin1, but all tables that were created during the deploy process are utf8, so this is one of these "dismiss this error message" thingy. But don't worry - I created a fix in TYPO3 to get this fixed in our master branch hopefully by tomorrow (https://review.typo3.org/#/c/50351/)

However, I will dig into the other problems showing up in the reports module to make sure we're "green".
