### ISSUE TITLE
Install Tool|Upgrade Wizard Charset

### ISSUE THREAD

**Issue by ksjogo** [platformsh/platformsh-example-typo3#20]
The Upgrade Wizard reports as uncompleted as the default db charset is not utf8. That's not changeable by us as far as I can see. So hide the warning.

**Comment by ksjogo** [comment]
@websi related?

**Comment by ferdynator** [comment]
I am currently running into issues with this. My configuration for a typo3 setup worked for multiple platform.sh projects already but stopped working recently. now the Installtool of a fresh Typo3 8.7 install breaks with this error message:

     ERROR: Invalid Charset
        Your database uses character set "latin1", but only "utf8" is supported
        with TYPO3. You probably want to change this before proceeding.

I have not found a way of changing the charset of my database service. Any idea how to proceed here?

**Comment by chadwcarlson** [comment]
@ferdynator Do you run into the same error working from our [typo3 template](https://github.com/platformsh-templates/typo3)? The template is our more maintained Typo3 example, and it looks like it contains some additional configuration not present in this repo.

**Comment by ferdynator** [comment]
Cannot test that right now, because we are working with typo3 8.7 not 10 as the other repo is. Ill try later on a test-branch. As far as I've read in #1 there was a possibility in older versions of typo3 introduced in the install-tool to skip  this error message. This cannot be done in either the CLI install nor the web install tool under 8.7 currently. 

For now we ended up copying the initialized database from another instance and go from there as it has become time-critical. But that is obviously not the desired solution....

**Comment by bmack** [comment]
@ferdynator the main issue is that the database created has "latin1" as character set. So ideally you log into your host / branch and modify the database itself to be "utf8" instead of "latin1" before installing TYPO3 v8.

**Comment by ferdynator** [comment]
here is what I do for now:

    mysql -h database.internal -U main -e "ALTER DATABASE main CHARACTER SET utf8 COLLATE utf8_general_ci;"

**Comment by Crell** [comment]
If that worked for you, @ferdynator, we can go ahead and close this, then retire this repo as it's not maintained.  Please confirm that you're OK for now.

**Comment by ferdynator** [comment]
Still having issues but they seem to be related to typo3 extensions, not typo3 itself. So yes I am ok for now, ty
